kind = "web"
previewPath = "/"
title = "SPORT LAND GYM"
version = "1.0.0"
id = "artifacts/sport-land-gym"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22958

[services.development]
run = "pnpm --filter @workspace/sport-land-gym run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/sport-land-gym", "run", "build" ]
publicDir = "artifacts/sport-land-gym/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22958"
BASE_PATH = "/"
